# Generated by Django 2.2.1 on 2019-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=1024)),
                ('author', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
