# Generated by Django 2.2.1 on 2019-09-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_auto_20190903_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
